
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage
import tkinter as tk
from config import SUPABASE
from collections import Counter
from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg
import matplotlib.pyplot as plt



OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\kevin\OneDrive\Documentos\TKINTER\Sistema-Desktop\assets_dashboard\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

def fetch_data():
    response = SUPABASE.table('core_pedido').select('*').execute()
    return response.data

def grafico_bebida():
    data = fetch_data()
    
    bebidas = [item['Bebida'] for item in data]
    contador = Counter(bebidas)

# Calculando as porcentagens
    total = sum(contador.values())
    percentuais = {chave: (valor / total) * 100 for chave, valor in contador.items()}

# Dados para o gráfico de pizza
    labels = percentuais.keys()
    sizes = percentuais.values()
    
    figure = plt.Figure(figsize=(5, 2), dpi=55)
    canvas = FigureCanvasTkAgg(figure)
    canvas.get_tk_widget().place(x=425, y=490)
    
    ax = figure.add_subplot(111)
    ax.pie(sizes, labels=labels, autopct='%1.1f%%', startangle=90, textprops={'color':"w"})
    ax.axis('equal')
    ax.set_title("Pedidos - Bebidas", color='white')
    
    figure.patch.set_facecolor('#181818')  # Fundo da figura
    ax.set_facecolor('#181818')  
        
    canvas.draw()
        
def grafico_acompanhamento():
    data = fetch_data()
    
    acompanhamentos = [item['Acompanhamento'] for item in data]
    contador = Counter(acompanhamentos)

# Calculando as porcentagens
    total = sum(contador.values())
    percentuais = {chave: (valor / total) * 100 for chave, valor in contador.items()}

# Dados para o gráfico de pizza
    labels = percentuais.keys()
    sizes = percentuais.values()
    
    figure = plt.Figure(figsize=(5, 2), dpi=55)
    canvas = FigureCanvasTkAgg(figure)
    canvas.get_tk_widget().place(x=130, y=490)
    
    ax = figure.add_subplot(111)
    ax.pie(sizes, labels=labels, autopct='%1.1f%%', startangle=90, textprops={'color':"w"})
    ax.axis('equal')
    ax.set_title("Pedidos - Acompanhamento", color='white')
    
    figure.patch.set_facecolor('#181818')  # Fundo da figura
    ax.set_facecolor('#181818')  
        
    canvas.draw()
    
def grafico_valor():
    data = fetch_data()
    
    summed_value = sum(item['Valor'] for item in data)

    figure = plt.Figure(figsize=(5, 3), dpi=60)
    canvas = FigureCanvasTkAgg(figure)
    canvas.get_tk_widget().place(x=130, y=270)
    ax = figure.add_subplot(111)
    
    categories = ['Total']
    values = [summed_value]

    ax.bar(categories, values)

    ax.set_title('Valor total arrecadado dos pedidos')
    
    #figure.patch.set_facecolor('#181818')  # Fundo da figura
    #ax.set_facecolor('#181818')  
        
    canvas.draw()
    
def grafico_status():
    data = fetch_data()
    
    status = [item['StatusPedido'] for item in data]
    contador = Counter(status)

    total = sum(contador.values())
    

    figure = plt.Figure(figsize=(5, 3), dpi=60)
    canvas = FigureCanvasTkAgg(figure)
    canvas.get_tk_widget().place(x=403, y=270)
    ax = figure.add_subplot(111)
    
    categories = ["Categorias"]
    values = [total]

    ax.bar(categories, values)

    ax.set_title('Quantidade de pedidos por categoria')
    
    #figure.patch.set_facecolor('#181818')  # Fundo da figura
    #ax.set_facecolor('#181818')  
        
    canvas.draw()


class Dashboard(tk.Frame):
    def __init__(self, parent, controller):
        super().__init__(parent)
        self.controller = controller

    window = Tk()

    window.title("Dashboard")
    window.geometry("1007x660")
    window.configure(bg = "#0B0B0B")


    canvas = Canvas(
        window,
        bg = "#0B0B0B",
        height = 660,
        width = 1007,
        bd = 0,
        highlightthickness = 0,
        relief = "ridge"
    )

    canvas.place(x = 0, y = 0)
    canvas.create_text(
        135.0,
        68.0,
        anchor="nw",
        text="Dashboard",
        fill="#FFFFFF",
        font=("RobotoSlab Medium", 28 * -1)
    )

    image_image_1 = PhotoImage(
        file=relative_to_assets("image_1.png"))
    image_1 = canvas.create_image(
        972.0,
        47.0,
        image=image_image_1
    )

    canvas.create_rectangle(
        130.0,
        482.0,
        411.0,
        606.0,
        fill="#181818",
        outline="")

    canvas.create_rectangle(
        443.0,
        122.0,
        707.0,
        246.0,
        fill="#181818",
        outline="")

    canvas.create_rectangle(
        135.0,
        122.0,
        397.0,
        246.0,
        fill="#181818",
        outline="")

    canvas.create_rectangle(
        426.0,
        482.0,
        707.0,
        606.0,
        fill="#181818",
        outline="")

    canvas.create_rectangle(
        131.0,
        264.0,
        706.0,
        462.0,
        fill="#181818",
        outline="")

    canvas.create_rectangle(
        754.0,
        122.0,
        990.0,
        606.0,
        fill="#181818",
        outline="")

    canvas.create_text(
        147.0,
        274.0,
        anchor="nw",
        text="Dados",
        fill="#FFFFFF",
        font=("RobotoSlab Medium", 20 * -1)
    )

    canvas.create_text(
        144.0,
        486.0,
        anchor="nw",
        text="Dados",
        fill="#FFFFFF",
        font=("RobotoSlab Regular", 20 * -1)
    )

    canvas.create_text(
        151.0,
        128.0,
        anchor="nw",
        text="Dados",
        fill="#FFFFFF",
        font=("RobotoSlab Regular", 20 * -1)
    )

    canvas.create_text(
        460.0,
        128.0,
        anchor="nw",
        text="Dados",
        fill="#FFFFFF",
        font=("RobotoSlab Regular", 20 * -1)
    )

    canvas.create_text(
        356.0,
        276.0,
        anchor="nw",
        text="Estoque",
        fill="#FFFFFF",
        font=("RobotoSlab Regular", 14 * -1)
    )

    canvas.create_text(
        463.0,
        276.0,
        anchor="nw",
        text="Vendas",
        fill="#FFFFFF",
        font=("RobotoSlab Regular", 14 * -1)
    )

    canvas.create_text(
        443.0,
        486.0,
        anchor="nw",
        text="Dados",
        fill="#FFFFFF",
        font=("RobotoSlab Regular", 20 * -1)
    )

    canvas.create_text(
        763.0,
        399.0,
        anchor="nw",
        text="Faltas no estoque desse mês",
        fill="#FFFFFF",
        font=("RobotoSlab Regular", 16 * -1)
    )

    canvas.create_text(
        765.0,
        150.0,
        anchor="nw",
        text="Melhores vendas desse mês",
        fill="#FFFFFF",
        font=("RobotoSlab Regular", 16 * -1)
    )

    canvas.create_text(
        833.0,
        330.0,
        anchor="nw",
        text="Ver mais",
        fill="#5F5F5F",
        font=("RobotoSlab Regular", 16 * -1)
    )

    canvas.create_text(
        833.0,
        570.0,
        anchor="nw",
        text="Ver mais",
        fill="#5F5F5F",
        font=("RobotoSlab Regular", 16 * -1)
    )

    canvas.create_rectangle(
        776.0,
        207.0,
        966.0,
        208.0,
        fill="#212121",
        outline="")

    canvas.create_rectangle(
        776.0,
        263.0,
        966.0,
        264.0,
        fill="#212121",
        outline="")

    canvas.create_rectangle(
        774.0,
        314.0,
        964.0,
        315.0,
        fill="#212121",
        outline="")

    canvas.create_rectangle(
        776.0,
        459.0,
        966.0,
        460.0,
        fill="#212121",
        outline="")

    canvas.create_rectangle(
        776.0,
        510.0,
        966.0,
        511.0,
        fill="#212121",
        outline="")

    canvas.create_rectangle(
        776.0,
        564.0,
        966.0,
        565.0,
        fill="#212121",
        outline="")

    canvas.create_rectangle(
        0.0,
        0.0,
        88.0,
        660.0,
        fill="#181818",
        outline="")

    button_image_1 = PhotoImage(
        file=relative_to_assets("button_1.png"))
    button_1 = Button(
        image=button_image_1,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: print("button_1 clicked"),
        relief="flat"
    )
    button_1.place(
        x=11.0,
        y=265.0,
        width=66.0,
        height=60.0
    )

    button_image_2 = PhotoImage(
        file=relative_to_assets("button_2.png"))
    button_2 = Button(
        image=button_image_2,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: print("button_2 clicked"),
        relief="flat"
    )
    button_2.place(
        x=11.0,
        y=188.0,
        width=66.0,
        height=60.0
    )

    image_image_2 = PhotoImage(
        file=relative_to_assets("image_2.png"))
    image_2 = canvas.create_image(
        46.0,
        41.0,
        image=image_image_2
    )

    button_image_3 = PhotoImage(
        file=relative_to_assets("button_3.png"))
    button_3 = Button(
        image=button_image_3,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: print("button_3 clicked"),
        relief="flat"
    )
    button_3.place(
        x=2.0,
        y=110.0,
        width=72.0,
        height=63.0
    )

    button_image_4 = PhotoImage(
        file=relative_to_assets("button_4.png"))
    button_4 = Button(
        image=button_image_4,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: print("button_4 clicked"),
        relief="flat"
    )
    button_4.place(
        x=9.0,
        y=514.0,
        width=66.0,
        height=60.0
    )

    button_image_5 = PhotoImage(
        file=relative_to_assets("button_5.png"))
    button_5 = Button(
        image=button_image_5,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: print("button_5 clicked"),
        relief="flat"
    )
    button_5.place(
        x=10.0,
        y=339.0,
        width=66.0,
        height=60.0
    )
    
    grafico_bebida()
    grafico_acompanhamento()
    grafico_valor()
    grafico_status()
    
    window.resizable(False, False)
    window.mainloop()
