
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage
import tkinter as tk

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\kevin\OneDrive\Documentos\TKINTER\Sistema-Desktop\assets_tela_inicial\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


class TelaInicial(tk.Frame):
    def __init__(parent):
        super().__init__(parent)
        

    window = Tk()

    window.title("Tela Inicial")
    window.geometry("1007x660")
    window.configure(bg = "#0B0B0B")


    canvas = Canvas(
        window,
        bg = "#0B0B0B",
        height = 660,
        width = 1007,
        bd = 0,
        highlightthickness = 0,
        relief = "ridge"
    )

    canvas.place(x = 0, y = 0)
    canvas.create_rectangle(
        0.0,
        0.0,
        502.0,
        660.0,
        fill="#3D1A56",
        outline="")

    canvas.create_text(
        547.0,
        238.0,
        anchor="nw",
        text="Acesse os relatórios",
        fill="#FFFFFF",
        font=("RobotoSlab Regular", 44 * -1)
    )

    image_image_1 = PhotoImage(
        file=relative_to_assets("image_1.png"))
    image_1 = canvas.create_image(
        251.0,
        344.0,
        image=image_image_1
    )

    button_image_1 = PhotoImage(
        file=relative_to_assets("button_1.png"))
    button_1 = Button(
        image=button_image_1,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: print("button_1 clicked"),
        relief="flat"
    )
    button_1.place(
        x=603.0,
        y=377.0,
        width=305.0,
        height=70.0
    )
    window.resizable(False, False)
    window.mainloop()
